name: Deployment to VM08

on:
  push:
    branches: [ "release" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Build and push images
        run: | 
          docker build -t ghcr.io/leo-iot/leo-iot-web/webapp:latest .
          docker image ls
          docker push ghcr.io/leo-iot/leo-iot-web/webapp
  vm08:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: install ssh key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VM08_PRIVATE_KEY }}

      - name: create .ssh/known_hosts
        run: |
          ssh-keyscan -H -t rsa -v ${{ secrets.VM_URL }}  >> ~/.ssh/known_hosts

      - name: install sshpass
        run: |
         sudo apt-get install sshpass

      - name: copy files to leo-vm
        run: |
          pwd
          sshpass -p '${{ secrets.VM08_PASSWORD }}' scp docker-compose.yaml ${{ secrets.VM08_USER }}@${{ secrets.VM08_URL }}:
          
