name: Deployment to VM08

on:
  push:
    branches: [ "release" ]
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/leo-iot/leo-iot-web

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Build and push images
        run: | 
          docker build -t ghcr.io/leo-iot/leo-iot-web/app:latest .
          docker image ls
          docker push ghcr.io/leo-iot/leo-iot-web/app
